### ISSUE TITLE
Fatal Error on CSV Export widget when searched value contains two words

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2034]
Video: https://www.loom.com/share/f0f0a743900f465c8d2bac7df1de0364

It happens when we search for field that has two or more words: https://debug.try.gravitykit.com/view/download-csv-widget-bug/?filter_1=Two+Words&mode=any#gv-view-2413-1

Error:

```
Fatal error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/includes/widgets/class-gravityview-widget-export-link.php:203 
Stack trace: 
#0 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/includes/widgets/class-gravityview-widget-export-link.php(203): printf() 
#1 /home//web/debug.try.gravitykit.com/public_html/wp-includes/class-wp-hook.php(324): GravityView_Widget_Export_Link->render_frontend() 
#2 /home//web/debug.try.gravitykit.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() 
#3 /home//web/debug.try.gravitykit.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() 
#4 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/includes/class-template.php(988): do_action() 
#5 /home//web/debug.try.gravitykit.com/public_html/wp-includes/class-wp-hook.php(324): GravityView_View->render_widget_hooks() 
#6 /home//web/debug.try.gravitykit.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() 
#7 /home//web/debug.try.gravitykit.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() 
#8 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/includes/class-api.php(1281): do_action() 
#9 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/templates/views/table/table-header.php(14): gravityview_before() 
#10 /home//web/debug.try.gravitykit.com/public_html/wp-includes/template.php(812): require('...') 
#11 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/future/lib/class-gamajo-template-loader.php(262): load_template() 
#12 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/future/lib/class-gamajo-template-loader.php(120): GV\Gamajo_Template_Loader->locate_template() 
#13 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/templates/views/table.php(16): GV\Gamajo_Template_Loader->get_template_part() 
#14 /home//web/debug.try.gravitykit.com/public_html/wp-includes/template.php(812): require('...') 
#15 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/future/lib/class-gamajo-template-loader.php(262): load_template() 
#16 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/future/lib/class-gamajo-template-loader.php(120): GV\Gamajo_Template_Loader->locate_template() 
#17 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/future/includes/class-gv-template-view.php(152): GV\Gamajo_Template_Loader->get_template_part() 
#18 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/future/includes/class-gv-renderer-view.php(209): GV\View_Template->render() 
#19 /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/future/includes/class-gv-view.php(439): GV\View_Renderer->render() 
#20 /home//web/debug.try.gravitykit.com/public_html/wp-includes/class-wp-hook.php(324): GV\View::content() 
#21 /home//web/debug.try.gravitykit.com/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters() 
#22 /home//web/debug.try.gravitykit.com/public_html/wp-includes/post-template.php(256): apply_filters() 
#23 /home//web/debug.try.gravitykit.com/public_html/wp-content/themes/hello-elementor/template-parts/single.php(25): the_content() 
#24 /home//web/debug.try.gravitykit.com/public_html/wp-includes/template.php(812): require('...') 
#25 /home//web/debug.try.gravitykit.com/public_html/wp-includes/template.php(745): load_template() 
#26 /home//web/debug.try.gravitykit.com/public_html/wp-includes/general-template.php(206): locate_template() #27 /home/gagatoguru1050/web/debug.try.gravitykit.com/public_html/wp-content/themes/hello-elementor/index.php(21): get_template_part() 
#28 /home//web/debug.try.gravitykit.com/public_html/wp-includes/template-loader.php(106): include('...') 
#29 /home//web/debug.try.gravitykit.com/public_html/wp-blog-header.php(19): require_once('...') 
#30 /home//web/debug.try.gravitykit.com/public_html/index.php(17): require('...') 
#31 {main} thrown in /home//web/debug.try.gravitykit.com/public_html/wp-content/plugins/gravityview/includes/widgets/class-gravityview-widget-export-link.php on line 203

```

Reproduced on GV 2.22.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2578618908/54016

**Comment by rafaehlers** [comment]
This was already tested, and the customer is already using a fixed version.
