### ISSUE TITLE
Fatal Error when Caching enabled

### ISSUE THREAD

**Issue by sneader** [GravityKit/GravityView#2130]
Just installed 2.28, using PHP 7.4 and WP 6.6.1.  When caching is enabled for one view, I am seeing a critical error on the front end, and the error_log shows:

[03-Sep-2024 02:27:52 UTC] PHP Fatal error:  Uncaught Error: Class 'GravityKit\GravityView\Foundation\Helpers\WP' not found in /home/username/public_html/wp-content/plugins/gravityview/includes/class-cache.php:478
Stack trace:
#0 /home/username/public_html/wp-content/plugins/gravityview/future/includes/class-gv-view.php(1517): GravityView_Cache->get()
#1 /home/username/public_html/wp-content/plugins/gravityview/future/includes/class-gv-view.php(1408): GV\View->run_db_query(Object(GF_Query))
#2 /home/username/public_html/wp-content/plugins/gravityview/future/includes/class-gv-renderer-view.php(72): GV\View->get_entries(Object(GV\Frontend_Request))
#3 /home/username/public_html/wp-content/plugins/gravityview/future/includes/class-gv-shortcode-gravityview.php(311): GV\View_Renderer->render(Object(GV\View), Object(GV\Frontend_Request))
#4 /home/username/public_html/wp-includes/shortcodes.php(434): GV\Shortcodes\gravityview->callback(Array, '', 'gravityview')
#5 [internal function]: do_shortcode_tag(Array)
#6 /home/username/public_html/wp-includes/shortcodes in /home/ssbstcom/public_html/wp-content/plugins/gravityview/includes/class-cache.php on line 478

Disabling caching for that view resolves the issue.
--------

### Additional information

**This issue happens in the following settings:**

- [?] View
- [X] Embedded via shortcode
- [?] Embedded via oEmbed

I am not familiar with testing these other options -- tell me how and I will try it.

**If shortcode, paste the shortcode below**

[gravityview id='1023']

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [X] No

**If yes, please drag a screenshot below:**

**Comment by mrcasual** [comment]
@sneader, thank you for reporting the issue. Was it working before with a previous version of GravityView?

**Comment by mrcasual** [comment]
@sneader, we are unable to replicate the issue. Could you please [get in touch with our support](https://www.gravitykit.com/support/) for further assistance?
